# Docker Compose Configuration File

# This YAML file defines a Docker Compose configuration with two services: "web" and "mydb".
# The "web" service uses the Odoo image (version 16.0) and depends on the "mydb" service.
# The "mydb" service uses the PostgreSQL image (version 15) and provides the database for Odoo.

version: '3.1'  # Especifica la versión de la configuración de Docker Compose que se utilizará.

services:
  # Servicio "web" que utiliza la imagen de Odoo (versión 16.0).
  web:
    image: odoo:16.0  # Establece la imagen Docker para el servicio "web".
    depends_on:
      - mydb  # Indica que este servicio depende de que el servicio "mydb" esté disponible.
    volumes: # Añade la sección "volumes" para el servicio "web"
      - ./addons:/mnt/extra-addons  # Monta el directorio local "./addons" dentro del contenedor en "/mnt/extra-addons"
    ports:
      - "8069:8069"  # Mapea el puerto 8069 del host al puerto 8069 del contenedor.
    environment:
      - HOST=mydb  # Configura la variable de entorno HOST con el valor "mydb".
      - USER=odoo  # Configura la variable de entorno USER con el valor "odoo".
      - PASSWORD=myodoo  # Configura la variable de entorno PASSWORD con el valor "myodoo".

  # Servicio "mydb" que utiliza la imagen de PostgreSQL (versión 15).
  mydb:
    image: postgres:15  # Establece la imagen Docker para el servicio "mydb".
    environment:
      - POSTGRES_DB=postgres  # Configura la variable de entorno POSTGRES_DB con el valor "postgres".
      - POSTGRES_PASSWORD=myodoo  # Configura la variable de entorno POSTGRES_PASSWORD con el valor "myodoo".
      - POSTGRES_USER=odoo  # Configura la variable de entorno POSTGRES_USER con el valor "odoo".
